[package]
name = "native_impl"
version = "0.1.0"
edition = "2024"

[dependencies]
linux-embedded-hal = "0.4.0"
embedded-hal = "1.0.0"

[profile.release]
debug = true

[lib]
name = "native_impl"
crate-type = ["lib"]

[[bin]]
name = "native_impl"
path = "src/main.rs"
bench = false